### PR TITLE
Update Octopus version to 14.1 (autotools)

### PR DESCRIPTION
**Pull request by iamashwin99**
Update octopus verison:
Latest release: [Octopus 14.1](https://octopus-code.org/download/14.1/octopus-14.1.tar.gz) (2024-05-03)

### CODE REVIEW

**Comment by iamashwin99** [comment]
The new 14.1 release explicitly asks for permission to continue the auto tools configure which breaks CI's.
Martin Leuders suggested to use ` --enable-silent-deprecation ` to ignore this.

**Review by fangohr — CHANGES_REQUESTED** [review]
Thank you. The current merge request looks good for autotools. I suggest the following additions and changes:

As the Octopus project is pushing for use of CMake, I think we should make the cmake-based build the default now. For 14.1, we could keep a different auto-tools based runner (that's what is done at the moment in this PR) but from 15.0 onwards it is not meant to work any more.

So from the user side, I would suggest:

1. Note in the README in the status section at the bottom that the current autotools builders for develop and stable are based on autotools, i.e. change "Debian Bookworm (12), Latest Octopus release (14.0)" to "Debian Bookworm (12), Latest Octopus release, autotools (14.0)", etc.

    When Octopus 15 comes along, we can remove those runners and badges.

2. Create two new builders: stable and develop using cmake instead of autotools. Update the README accordingly to show badges. These are the two builders and badges we will keep in the long run.

**Comment by iamashwin99** [comment]
I have now updated the readme to explicitly mention the autotools.

For the docker images to be pushed to docker hub, do you want them to be from autotools or make?
or in other words, should we create the cmake images within this MR ( which I expect might have pitfalls ) or should we do it in a separate MR.

**Comment by fangohr** [comment]
Can be in a separate MR if you prefer. 

I want to use the cmake build for the docker image. 

As I did the image build and push to dockerhub manually in the past, we can leave it like that for now.

**Comment by iamashwin99** [comment]
As discussed today, we could do the cmake update in a separate MR and keep this MR just for autotools.

**Pull request merged**
